### ISSUE TITLE
AppImage not starting

### ISSUE THREAD

**Issue by stefonarch** [greymass/eos-voter#123]
```
$ ./eos-voter-0.1.7-x86_64.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_eos-vo0gMnhM/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3


```
linux-unpacked/eos-voter is starting.

SO Arch Linux

**Comment by aaroncox** [comment]
Related to #49 

There's an issue with the most recent version of electron-builder that's causing this.
