### ISSUE TITLE
wallet doesn't support token without dot

### ISSUE THREAD

**Issue by baseloo** [greymass/eos-voter#1370]
### Description

created a token with the name "NDOLLAR" and max supply as the trx below 
https://explorer.telos.net/transaction/5a4c58231455525f00d6bc3b2edcd46b2d3824369c42850f8dfcdff48529d0c4
You can see the token is without a dot and any digits after it.

I got this error message in the transfer process 

![image](https://github.com/greymass/anchor/assets/44838543/290f3343-4a12-42a4-a8de-e76d8589a197)

Thank you,

### Platform

Desktop (Windows)

### Steps To Reproduce

new token with name.
add max supply without DOT.
try to transfer from account a to b.

### Relevant log output

```shell
Error: Number 15372286728091292160000 overflows int64
    at new E (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:519249)
    at new x (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:523159)
    at Function.from (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:521546)
    at t.convertFloat (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:549240)
    at Function.fromFloat (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:547471)
    at Function.from (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:547069)
    at s.value (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2445480)
    at Wa (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4418375)
    at za (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4418170)
    at Su (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4453784)
```

### Contact Details

basel.k@eosarabia.net

**Comment by aaroncox** [comment]
What was the input amount you entered to transfer? That number does look larger than the supply

**Comment by baseloo** [comment]
The error occurred before the input for the amount, just by selecting the token from the token list.
![image](https://github.com/greymass/anchor/assets/44838543/76515e0f-3767-458b-ad03-c83eee40e491)
