### ISSUE TITLE
It says a transaction may have gone through that wasnt supposed to but this is false. it failed, i need an adult. 

### ISSUE THREAD

**Issue by UntangledSapphire** [greymass/eos-voter#1376]
### Description

TypeError: Cannot read property 'EOS5tE1rwSYCtgXuxjeDRa36yfQkdkYCwCTmL6EUzc9o5i6AceADJ' of undefined
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2210302
    at Array.map (<anonymous>)
    at a.value (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:2209573)
    at Wa (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4418406)
    at za (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4418201)
    at Su (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4453815)
    at vc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4445256)
    at yc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4445181)
    at uc (file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4442211)
    at file:///C:/Program%20Files/Anchor%20Wallet/resources/app.asar/dist/renderer.main.prod.js:2:4393852

### Platform

Desktop (MacOS)

**Comment by aaroncox** [comment]
This error seems to indicate it can't pull the key from storage. It sounds like either the local data storage got removed/corrupted on the machine, or maybe Anchor just needs a good restart? 

Have you tried to completely restart Anchor, and unlock it again?

If that doesn't work - do you have any backups that could be used to restore the account(s)?

If you need further support for this, it'll probably be easier to go through support@greymass.com rather than through github issues. We admittedly don't see responses on these as easily as we do through the support portal.
