### ISSUE TITLE
Blank Eos Voter 0.4.1

### ISSUE THREAD

**Issue by jerrydv** [greymass/eos-voter#286]
<img width="799" alt="screen shot 2018-08-01 at 4 13 12 pm" src="https://user-images.githubusercontent.com/33798855/43509746-0d4edb02-95a6-11e8-8267-6cfb77788510.png">

Blank eos-voter tab. What should I do? I also deleted and reinstalled the app several times.

**Comment by lukestokes** [comment]
I've noticed this a few times lately as well. Here's what I see in the developer tools:
```
apigen.js:90 POST https://eos.greymass.com/v1/chain/get_currency_balance 500 ()
(anonymous) @ apigen.js:90
t @ accounts.js:235
qt @ lodash.js:516
Gi @ lodash.js:9341
(anonymous) @ accounts.js:233
(anonymous) @ index.js:8
dispatch @ redux.js:563
r.node.r.node.length.getAccount.then.n @ accounts.js:104
react-dom.production.min.js:187 Error: Cannot get property 'react' on missing remote object 382
Error: Cannot get property 'react' on missing remote object 382
    at throwRPCError (/Applications/eos-voter.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/eos-voter.app/Contents/Resources/electron.asar/browser/rpc-server.js:384:7)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/Applications/eos-voter.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at throwRPCError (/Applications/eos-voter.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/eos-voter.app/Contents/Resources/electron.asar/browser/rpc-server.js:384:7)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/Applications/eos-voter.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Applications/eos-voter.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Applications/eos-voter.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.descriptor.get [as react] (/Applications/eos-voter.app/Contents/Resources/electron.asar/renderer/api/remote.js:132:16)
    at new t (file:///Applications/eos-voter.app/Contents/Resources/app.asar/dist/renderer.basic.prod.js:73:95379)
    at ks (file:///Applications/eos-voter.app/Contents/Resources/app.asar/dist/renderer.basic.prod.js:73:64688)
    at li (file:///Applications/eos-voter.app/Contents/Resources/app.asar/dist/renderer.basic.prod.js:73:76983)
    at ci (file:///Applications/eos-voter.app/Contents/Resources/app.asar/dist/renderer.basic.prod.js:73:77290)
    at Gi (file:///Applications/eos-voter.app/Contents/Resources/app.asar/dist/renderer.basic.prod.js:73:80864)
    at zi (file:///Applications/eos-voter.app/Contents/Resources/app.asar/dist/renderer.basic.prod.js:73:80335)
    at Qi (file:///Applications/eos-voter.app/Contents/Resources/app.asar/dist/renderer.basic.prod.js:73:80161)
Rs @ react-dom.production.min.js:187
n.callback @ react-dom.production.min.js:194
Ur @ react-dom.production.min.js:143
Qr @ react-dom.production.min.js:144
qi @ react-dom.production.min.js:219
Gi @ react-dom.production.min.js:211
zi @ react-dom.production.min.js:210
Qi @ react-dom.production.min.js:210
Fi @ react-dom.production.min.js:208
hi @ react-dom.production.min.js:206
enqueueSetState @ react-dom.production.min.js:147
_.setState @ react.production.min.js:12
i.onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
e.notifyNestedSubs @ Subscription.js:65
i.onStateChange @ connectAdvanced.js:202
forEach.e @ setup-electron-store.js:44
callListeners @ setup-electron-store.js:44
d.dispatch.n @ setup-electron-store.js:95
(anonymous) @ middleware.js:13
(anonymous) @ index.js:11
dispatch @ redux.js:563
c.node.c.node.length.getActions.then.t @ accounts.js:165
Promise resolved (async)
(anonymous) @ accounts.js:157
(anonymous) @ index.js:8
(anonymous) @ redux.js:449
setState @ Actions.js:74
Ur @ react-dom.production.min.js:143
Qr @ react-dom.production.min.js:144
qi @ react-dom.production.min.js:219
Gi @ react-dom.production.min.js:211
zi @ react-dom.production.min.js:210
Qi @ react-dom.production.min.js:210
Fi @ react-dom.production.min.js:208
hi @ react-dom.production.min.js:206
enqueueSetState @ react-dom.production.min.js:147
_.setState @ react.production.min.js:12
i.onStateChange @ connectAdvanced.js:205
notify @ Subscription.js:26
e.notifyNestedSubs @ Subscription.js:65
i.onStateChange @ connectAdvanced.js:202
forEach.e @ setup-electron-store.js:44
callListeners @ setup-electron-store.js:44
d.dispatch.n @ setup-electron-store.js:95
(anonymous) @ middleware.js:13
(anonymous) @ index.js:11
dispatch @ redux.js:563
c.node.c.node.length.getActions.then.t @ accounts.js:165
apigen.js:120 api < error 	 {message: "Table accounts is not specified in the ABI", file: "chain_plugin.cpp", line_number: 983, method: "get_table_type"} https://eos.greymass.com/v1/chain/get_currency_balance {"code":"*********","account":"*********","symbol":"CETOS"}
(anonymous) @ apigen.js:120
apigen.js:121 Error: {"code":500,"message":"Internal Service Error","error":{"code":3060003,"name":"contract_table_query_exception","what":"Contract Table Query Exception","details":[{"message":"Table accounts is not specified in the ABI","file":"chain_plugin.cpp","line_number":983,"method":"get_table_type"}]}}
    at apigen.js:95
    at <anonymous>
```

**Comment by Drug0j** [comment]
pkill eos-voter 0.4....

**Comment by Drug0j** [comment]
Start the Task Manager and go to the system level, try to start with the command sudo ./eos-voter

**Comment by aaroncox** [comment]
We've noticed this as well, it's like the internet electron processes are dying and no longer responding. A restart generally fixes it, and we'll continue looking into this until we can get it resolved.

**Comment by dabana** [comment]
I have the same issue with eos-voter 0.4.1 on windows 10 installing from the exe installer.  It shows "loading" at the top left for less that a second and then nothing... forever.

**Comment by aaroncox** [comment]
Closing out old issues. We have identified a few reasons this happens and fixed them, but there's still a couple outstanding we're working to find.
