### ISSUE TITLE
Error message when entering local wallet password in Hot Wallet

### ISSUE THREAD

**Issue by franceraq** [greymass/eos-voter#644]
I get an error message when I do the following steps when trying to set up my hot wallet:

1. Enter my private key
2. Select my account ending in **@active**
3. Click on **Import Accounts**
4. Enter my local wallet password

As soon as I enter my local wallet password, I get an error message.

![image](https://user-images.githubusercontent.com/51112111/58462319-30fb5080-8164-11e9-8c89-d9a54224d41c.png)

This is the error message:

TypeError: Cannot read property 'includes' of undefined
    at Object.render (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:1:62678)
    at us (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:59850)
    at ls (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:59645)
    at fs (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:63322)
    at Ks (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:78434)
    at Qs (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:78811)
    at Oa (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:85234)
    at Ia (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:84614)
    at wa (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:83635)
    at $s (file:///Applications/Anchor-BETA.app/Contents/Resources/app.asar/dist/renderer.main.prod.js:91:82538)

**Comment by aaroncox** [comment]
I was able to reproduce, and have a fix setup for the next release. Once that release is out, this issue will be marked as resolved.
